<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>7.5.0</Version>
    <AssemblyVersion>7.5.0.0</AssemblyVersion>
    <FileVersion>7.5.0.0</FileVersion>
    <InformationalVersion>7.5.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>false</PublishReadyToRun>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**;bin\**;.mcps-build\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Resource Include="Assets\background.jpg" />
    <Resource Include="Assets\MapleMono.ttf" />
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\mc-profile-icon.png" />
    <EmbeddedResource Include="Assets\WikiEntries.txt" />
  </ItemGroup>

</Project>
